### ISSUE TITLE
Categories should always be deleted when included

### ISSUE THREAD

**Issue by Daimona** [valerio-bozzolan/MediaWikiOrphanizerBot#13]
Categories are special-case wikilinks. When used with the colon ([[:category:xxx]]) they should be handled like wlinks. But when used without the colon, they should always be deleted completely.

**Comment by valerio-bozzolan** [comment]
Yep.

It could be __very__ useful a removeCategory() method from the `Wikitext` class, aside of the `addCategory()` one.

**Comment by Daimona** [comment]
https://github.com/valerio-bozzolan/boz-mw/pull/2
