### ISSUE TITLE
Fix [[ :pluto_paolo piero ]]

### ISSUE THREAD

**Issue by valerio-bozzolan** [valerio-bozzolan/MediaWikiOrphanizerBot#5]
Investigate why it didn't match the corner case `[[ :pluto_paolo piero ]]` [here](https://it.wikipedia.org/w/index.php?title=Utente:Valerio_Bozzolan/Sandbox6&diff=prev&oldid=102487923).

**Comment by Daimona** [comment]
Sherlock Holmes at your service! The links prop returns it, so there should be a problem with regexps. Basing on my 20 seconds tour of the Wikilink class, I think you should (optionally) add the colon to the regex at line 157.

**Comment by valerio-bozzolan** [comment]
Actually I've seen it runs these 2 kind of regexes:

    \[\[(?P<title>:?[ _]*[Pp]luto[ _]+paolo[ _]+piero)\]\]
    \[\[:?[ _]*[Pp]luto[ _]+paolo[ _]+piero([ _]*\|(?P<alias>[ %!\"$&'()*,\-.\/0-9:;=?@A-Z\\^_`a-z~\x80-\xFF+#<>\[\]{}\n\t]*?))?\]\]

So it's only a problem related to the spaces/tabs hamburger.
